### PR TITLE
Split into multiple packages and remove special types

### PR DESCRIPTION
**Pull request by andrewvc**
This PR splits the whole lib into multiple packages and removes the special `Map/Slice/Scalar` types replacing them with plain `map[string]interface{}`, `[]interface{}`, and `interface{}`.

Currently it's all sort of mashed into the core `lookslike` package. As we add more `IsDef` types in the future this will get hard to handle. This refactor creates a number of packages to do this while keeping the DSL simple, while at the same time avoiding cycles.

### CODE REVIEW

**Comment by andrewvc** [comment]
This is a giant PR, but doesn't change any functionality in any meaningful way, it just splits up the packages.

**Comment by urso** [comment]
Disclaimer: haven't had time to fully dive into the change yet. But some comments so to start some discussion.

I see the motivation, still I'm not sure about the split. Especially about the granularity.

Some notes about package naming:
- it's uncommon to pluralize names
- do not take away good packages names (e.g. result/path/validator are pretty generic)

E.g. see [blog post by Rakyll](https://rakyll.org/style-packages/), and [golang.org blog post](https://blog.golang.org/package-names).

**Comment by andrewvc** [comment]
@urso I admit the granularity is weird. My goal was to break things up such that the `isdef` could be in a separate package. That required breaking out common things into packages.

I've pushed an update that un-pluralizes things. It also renamed packages like `paths` to `llpath` (`ll` for `lookslike`). Is that more go-like?

I do think this granularity makes things much more maintainable.

**Comment by andrewvc** [comment]
I'll also add that it makes contributions simpler since everything isn't complected into one giant namespace as before.

**Comment by urso** [comment]
I'm fine with prefixing the names. The `llutil` makes me cry, though. If possible we should not name packages `util`, `common`, or `helper`. Also consider to have an `internal/<x>` package for utility packages/functionality not to be exported.

We really need the llresults package?

**Comment by andrewvc** [comment]
I've moved `llutil` into `internal/llreflect`, since the only functions there have to do with reflection.

We need `llresults` as a separate package to prevent circular dependencies unfortunately.

**Pull request merged**
